# Whenever the `main` branch changes,
# deploy a tiny Bazel registry to GitHub Pages
# containing the most recent handful of commits from `main` as versions.
#
# The Bazel registry is a simple static directory with a specific format.
# https://bazel.build/external/registry

name: Automatic Bazel Registry
on:
  push:
    branches:
      - 'main'
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: vimana-cloud/vimana/.github/workflows/auto-registry.yaml@main
